# Infrastructure Docker Compose
# Shared infrastructure services for all applications on this VPS
# Services: Caddy (reverse proxy + SSL), Dockhand (container management)

services:
   # Caddy Web Server (Reverse Proxy and SSL Termination)
   caddy:
      image: caddy:latest
      container_name: caddy
      restart: unless-stopped
      ports:
         - "80:80" # HTTP (redirects to HTTPS)
         - "443:443" # HTTPS
      volumes:
         - ./Caddyfile:/etc/caddy/Caddyfile:ro # Read-only Caddyfile
         - caddy_data:/data # Persist SSL certificates
         - caddy_config:/config # Persist Caddy config
         - caddy_logs:/var/log/caddy # Persist logs
      networks:
         - caddy_network # Shared network for routing to apps
      healthcheck:
         test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
         interval: 30s
         timeout: 10s
         retries: 3
         start_period: 10s

   # Dockhand
   dockhand:
      image: fnsys/dockhand:latest
      container_name: dockhand
      restart: unless-stopped
      # Expose Dockhand on a custom port (you can use Tailscale to access this securely from your local machine)
      ports:
         - "9001:9000"
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock # Access Docker daemon (required for Dockhand to manage containers)
         - dockhand_data:/app/data # persist Dockhand data
      networks:
         - private_network

   # Bugsink - Lightweight Error Monitoring (Sentry-compatible)
   bugsink:
      image: bugsink/bugsink:latest
      container_name: bugsink
      restart: unless-stopped
      # Expose Bugsink on a custom port (you can use Tailscale to access this securely from your local machine)
      ports:
         - "8001:8000"
      environment:
         SECRET_KEY_FILE: /run/secrets/bugsink_secret_key
         # TODO: Set ALLOWED_HOSTS and BASE_URL to your actual domain in production
         ALLOWED_HOSTS: bugsink,bugsink-ingest.example.com
         BASE_URL: https://bugsink-ingest.example.com

         USER_REGISTRATION: CB_NOBODY # Disable new user registration
         CREATE_SUPERUSER: ${BUGSINK_ADMIN_EMAIL}:${BUGSINK_ADMIN_PASSWORD}
         # Uses SQLite by default (no separate database needed)
      volumes:
         - bugsink_data:/data # persist Bugsink data
      secrets:
         # Master secret for Bugsink backend cryptographic signing (sessions, cookies, tokens).
         # Required for both API and UI security—do not share or expose.
         - bugsink_secret_key
      networks:
         - caddy_network
      healthcheck:
         test:
            ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8000/ || exit 1"]
         interval: 30s
         timeout: 10s
         retries: 3
         start_period: 15s

# Shared Docker network for reverse proxy routing
# Application containers will connect to this network to be accessible via Caddy
networks:
   caddy_network:
      name: caddy_network
      driver: bridge
   private_network:
      name: private_network
      driver: bridge

# Named Docker volumes for persistent data
volumes:
   caddy_data:
      name: myinfra_caddy_data
   caddy_config:
      name: myinfra_caddy_config
   caddy_logs:
      name: myinfra_caddy_logs
   bugsink_data:
      name: myinfra_bugsink_data
   dockhand_data:
      name: myinfra_dockhand_data

# Docker secrets for sensitive data
secrets:
   bugsink_secret_key:
      file: ./secrets/bugsink_secret_key.txt
